# Generated by Django 5.2.4 on 2025-09-19 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(default='UN', max_length=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to='inventory.item')),
            ],
        ),
    ]
