# Generated by Django 5.2.4 on 2025-09-19 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sku']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo atual'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(max_length=180, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=40, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.CharField(default='un', max_length=15, verbose_name='Unidade'),
        ),
        migrations.DeleteModel(
            name='Saldo',
        ),
    ]
